name: PR Compliance

on:
  pull_request_target:
    branches: ['main']
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  remind:
    name: Changelog
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot' && github.actor != 'dependabot[bot]' && github.actor != 'github-actions' && github.actor != 'github-actions[bot]' && github.event.pull_request.draft == false }}
    steps:
    - uses: actions/checkout@v5
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.3.0
      with:
        changelog_regex: 'CHANGELOG.md'
        customPrMessage: |
          👋 Hey there! It looks like the changelog might need an update.

          Please take a moment to edit the [`CHANGELOG.md`](/qBraid/pyqasm/blob/main/CHANGELOG.md) with:
          - A brief, one-to-two sentence summary of your changes.
          - A link back to this PR for reference.
          - (Optional) A small working example if you've added new features.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}